# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastname',
            field=models.CharField(blank=True, max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, max_length=30, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telephonenum',
            field=models.CharField(blank=True, max_length=10, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telephonenum2',
            field=models.CharField(blank=True, max_length=10, verbose_name='Телефонный номер#2'),
        ),
    ]
