# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_auto_20181026_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения *ДД.ММ.ГГГГ*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, max_length=30, verbose_name='Номер кабинета'),
        ),
    ]
