# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technic',
            fields=[
                ('technic_id', models.AutoField(primary_key=True, serialize=False)),
                ('inventorynum1', models.CharField(blank=True, max_length=50, verbose_name='Инвентарный номер#1')),
                ('inventorynum2', models.CharField(blank=True, max_length=50, verbose_name='Инвентарный номер#2')),
                ('serialnum', models.CharField(blank=True, max_length=50, verbose_name='Серийный номер')),
                ('technictype', models.CharField(choices=[('CMT', 'КМТ'), ('SERVER', 'Сервер'), ('WORKSTATION', 'Компьютер'), ('CERT', 'Сертификат'), ('FLASH', 'Флеш-накопитель'), ('TOKEN', 'Токен')], max_length=50, verbose_name='Тип техники')),
            ],
            options={
                'verbose_name': 'Техника',
                'verbose_name_plural': 'Техника',
                'ordering': ['technic_id'],
            },
        ),
    ]
