# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serversapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tehnic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventorynum1', models.CharField(help_text='Инвентарный номер#1', max_length=50)),
                ('inventorynum2', models.CharField(help_text='Инвентарный номер#2', max_length=50)),
                ('serialnum', models.CharField(help_text='Серийный номер', max_length=50)),
                ('technictype', models.CharField(choices=[('CMT', 'КМТ'), ('SRV', 'Сервер'), ('W', 'Компьютер'), ('CRT', 'Сертификат'), ('FC', 'Флеш-накопитель'), ('TC', 'Токен')], default='CMT', help_text='Тип техники', max_length=50)),
                ('tecnic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='serversapp.Server')),
            ],
        ),
    ]
