# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentmname', models.CharField(max_length=100, null=True, verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
                'ordering': ['departmentmname'],
            },
        ),
        migrations.CreateModel(
            name='SubDevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdevisionname', models.CharField(max_length=100, null=True, verbose_name='Отдел')),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['subdevisionname'],
            },
        ),
        migrations.CreateModel(
            name='Technic',
            fields=[
                ('technic_id', models.AutoField(primary_key=True, serialize=False)),
                ('inventorynum1', models.CharField(blank=True, max_length=50, verbose_name='Инвентарный номер#1')),
                ('inventorynum2', models.CharField(blank=True, max_length=50, verbose_name='Инвентарный номер#2')),
                ('serialnum', models.CharField(blank=True, max_length=50, verbose_name='Серийный номер')),
                ('technictype', models.CharField(choices=[('CMT', 'КМТ'), ('SERVER', 'Сервер'), ('WORKSTATION', 'Компьютер'), ('CERT', 'Сертификат'), ('FLASH', 'Флеш-накопитель'), ('TOKEN', 'Токен')], max_length=50, verbose_name='Тип техники')),
            ],
            options={
                'verbose_name': 'Техника',
                'verbose_name_plural': 'Техника',
                'ordering': ['technic_id'],
            },
        ),
    ]
