# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tehnic',
            name='technictype',
            field=models.CharField(choices=[('CMT', 'КМТ'), ('SERVER', 'Сервер'), ('WORKSTATION', 'Компьютер'), ('CERT', 'Сертификат'), ('FLASH', 'Флеш-накопитель'), ('TOKEN', 'Токен')], default='CMT', help_text='Тип техники', max_length=50),
        ),
    ]
