# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentmname', models.CharField(max_length=50, null=True, verbose_name='Департамент')),
            ],
        ),
        migrations.CreateModel(
            name='SubDevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdevisionname', models.CharField(max_length=50, null=True, verbose_name='Отдел')),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Department', verbose_name='Департамент')),
            ],
        ),
    ]
