# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serversapp', '0003_auto_20181012_1616'),
        ('mainapp', '0002_auto_20181012_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventorynum1', models.CharField(help_text='Инвентарный номер#1', max_length=50)),
                ('inventorynum2', models.CharField(help_text='Инвентарный номер#2', max_length=50)),
                ('serialnum', models.CharField(help_text='Серийный номер', max_length=50)),
                ('technictype', models.CharField(choices=[('CMT', 'КМТ'), ('SERVER', 'Сервер'), ('WORKSTATION', 'Компьютер'), ('CERT', 'Сертификат'), ('FLASH', 'Флеш-накопитель'), ('TOKEN', 'Токен')], default='CMT', help_text='Тип техники', max_length=50)),
                ('technic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='serversapp.Server')),
            ],
            options={
                'verbose_name': 'Техника',
                'verbose_name_plural': 'Техника',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='tehnic',
            name='tecnic',
        ),
        migrations.DeleteModel(
            name='Tehnic',
        ),
    ]
