# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20181030_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=1000, verbose_name='Контент')),
                ('type', models.CharField(choices=[('Главные', 'MAIN'), ('Побочные', 'SECOND')], max_length=50, verbose_name='Тип новости')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['title'],
            },
        ),
    ]
