# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='departmentmname',
            field=models.CharField(max_length=100, null=True, verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='subdevision',
            name='subdevisionname',
            field=models.CharField(max_length=100, null=True, verbose_name='Отдел'),
        ),
    ]
