# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('technic_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip', models.CharField(help_text='Ip-адрес', max_length=50)),
                ('name', models.CharField(help_text='Имя', max_length=50)),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Серверы',
                'ordering': ['name'],
            },
        ),
    ]
