# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serversapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='technic_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
