# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serversapp', '0002_auto_20181203_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['name'], 'verbose_name': 'Сервер', 'verbose_name_plural': 'Серверы'},
        ),
    ]
