# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-25 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=30, verbose_name='Фамилия Имя Отчество')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('telephonenum', models.CharField(blank=True, max_length=10, verbose_name='Телефонный номер')),
                ('telephonenum2', models.CharField(blank=True, max_length=10, verbose_name='Телефонный номер#2')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Номер кабинета')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['fio'],
                'permissions': (('can_view_employeeslist', 'Может просматривать список сотрудников'), ('can_add_employees', 'Может добавлять сотрудников'), ('can_edit_employees', 'Может изменять карточки сотрудников'), ('can_delete_employees', 'Может удалять карточки сотрудников')),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=75, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['postname'],
            },
        ),
    ]
