# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 14:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=30, verbose_name='Фамилия Имя Отчество')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('telephonenum', models.CharField(blank=True, max_length=10, verbose_name='Телефонный номер')),
                ('telephonenum2', models.CharField(blank=True, max_length=10, verbose_name='Телефонный номер#2')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Номер кабинета')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография')),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Department', verbose_name='Управление')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['fio'],
                'permissions': (('can_view_employeeslist', 'Может просматривать список сотрудников'), ('can_add_employees', 'Может добавлять сотрудников'), ('can_edit_employees', 'Может изменять карточки сотрудников'), ('can_delete_employees', 'Может удалять карточки сотрудников')),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=75, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['postname'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employeesapp.Post', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='employee',
            name='subdevision',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.SubDevision', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
