# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('telephonenum', models.CharField(blank=True, max_length=10, verbose_name='Телефонный номер')),
                ('telephonenum2', models.CharField(blank=True, max_length=10, verbose_name='Телефонный номер#2')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Номер кабинета')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
