# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20181030_1127'),
        ('employeesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Department', verbose_name='Управление'),
        ),
        migrations.AddField(
            model_name='employee',
            name='subdevision',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.SubDevision', verbose_name='Отдел'),
        ),
    ]
