# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['fio'], 'permissions': (('can_view_employeeslist', 'Может просматривать список сотрудников'), ('can_add_employees', 'Может добавлять сотрудников'), ('can_edit_employees', 'Может изменять карточки сотрудников'), ('can_delete_employees', 'Может удалять карточки сотрудников')), 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
