# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0002_auto_20181030_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='patronymic',
        ),
        migrations.AddField(
            model_name='employee',
            name='fio',
            field=models.CharField(blank=True, max_length=30, verbose_name='Фамилия Имя Отчество'),
        ),
    ]
