# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0004_auto_20181030_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=30, verbose_name='Должность')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employeesapp.Post', verbose_name='Должность'),
        ),
    ]
