# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0007_auto_20181030_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='subdevision',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.SubDevision', verbose_name='Отдел'),
        ),
    ]
