# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0009_auto_20181030_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='img',
            field=models.ImageField(height_field=100, null=True, upload_to='C:\\Users\\d051a\\Desktop\\pythonnoobs_firstproject\\firstproject\\ACCOUNTING/media', width_field=100),
        ),
    ]
