# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0010_employee_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\d051a\\Desktop\\pythonnoobs_firstproject\\firstproject\\ACCOUNTING/media'),
        ),
    ]
