# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0011_auto_20181123_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postname',
            field=models.CharField(max_length=50, verbose_name='Должность'),
        ),
    ]
