# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0012_auto_20181130_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postname',
            field=models.CharField(max_length=75, verbose_name='Должность'),
        ),
    ]
