# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeesapp', '0014_auto_20181203_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['fio'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['postname'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
    ]
