# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название праздника')),
                ('date', models.DateField(verbose_name='Дата праздника')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
            ],
            options={
                'verbose_name': 'Праздник',
                'verbose_name_plural': 'Празники',
            },
        ),
    ]
