# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-09 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название праздника')),
                ('date', models.DateField(verbose_name='Дата праздника')),
                ('short_description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
            ],
        ),
    ]
