# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-09 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventorynum', models.CharField(max_length=12)),
                ('serialnum', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('netbiosname', models.CharField(max_length=200)),
                ('ip', models.GenericIPAddressField()),
                ('macaddress', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
                'permissions': (('can_view_workstationslist', 'Может просматривать список компьютеров'), ('can_add_workstations', 'Может добавлять компьютер'), ('can_edit_workstations', 'Может изменять карточки компьютеров'), ('can_delete_workstations', 'Может удалять карточки компьютеров')),
            },
        ),
        migrations.CreateModel(
            name='WorkstationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computermodelname', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Модель компьютера',
                'verbose_name_plural': 'Модели компьютера',
            },
        ),
        migrations.AddField(
            model_name='workstation',
            name='computermodelname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workstationsapp.WorkstationModel'),
        ),
    ]
