# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventorynum', models.CharField(max_length=12)),
                ('serialnum', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('netbiosname', models.CharField(max_length=200)),
                ('ip', models.GenericIPAddressField()),
                ('macaddress', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Computer',
                'verbose_name_plural': 'Computers',
            },
        ),
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('computermodel_id', models.AutoField(primary_key=True, serialize=False)),
                ('computermodelname', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ComputerModel',
                'verbose_name_plural': 'ComputerModels',
            },
        ),
        migrations.AddField(
            model_name='computer',
            name='computermodel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workstationsapp.ComputerModel'),
        ),
        migrations.AddField(
            model_name='computer',
            name='computermodelname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workstationsapp.ComputerModel'),
        ),
    ]
