# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workstationsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer',
            options={'permissions': (('can_view_workstationslist', 'Может просматривать список компьютеров'), ('can_add_workstations', 'Может добавлять компьютер'), ('can_edit_workstations', 'Может изменять карточки компьютеров'), ('can_delete_workstations', 'Может удалять карточки компьютеров')), 'verbose_name': 'Компьютер', 'verbose_name_plural': 'Компьютеры'},
        ),
    ]
