# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workstationsapp', '0002_auto_20181203_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer',
            options={'verbose_name': 'Computer', 'verbose_name_plural': 'Computers'},
        ),
        migrations.AlterModelOptions(
            name='computermodel',
            options={'verbose_name': 'ComputerModel', 'verbose_name_plural': 'ComputerModels'},
        ),
    ]
