# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workstationsapp', '0003_auto_20181203_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'Computer', 'verbose_name_plural': 'Computers'},
        ),
        migrations.AlterModelOptions(
            name='computermodel',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'ComputerModel', 'verbose_name_plural': 'ComputerModels'},
        ),
    ]
