# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-25 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employeesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainproblemname', models.CharField(max_length=50, null=True, verbose_name='Типовая проблема')),
            ],
            options={
                'verbose_name': 'Типовая проблема',
                'verbose_name_plural': 'Типовые проблемы',
                'ordering': ['mainproblemname'],
            },
        ),
        migrations.CreateModel(
            name='SubProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subproblemname', models.CharField(max_length=50, null=True, verbose_name='Проблема')),
                ('mainproblem', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ticketsapp.MainProblem', verbose_name='Типовая проблема')),
            ],
            options={
                'verbose_name': 'Проблема',
                'verbose_name_plural': 'Проблемы',
                'ordering': ['subproblemname'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Открыта'), ('INWORK', 'В работе'), ('CLOSED', 'Выполнено')], default='OPEN', max_length=50, verbose_name='Статус заявки')),
                ('priority', models.CharField(choices=[('LOW', 'Низкий'), ('NORMAL', 'Обычный'), ('HIGH', 'Высокий')], default='NORMAL', max_length=50, verbose_name='Приоритет')),
                ('description', models.CharField(max_length=300, verbose_name='Описание проблемы')),
                ('note', models.CharField(blank=True, default='-', max_length=300, null=True, verbose_name='Примечание')),
                ('userhostname', models.CharField(blank=True, max_length=10, null=True, verbose_name='Имя компьютера')),
                ('timestarted', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время подачи заявки')),
                ('timeclosed', models.DateTimeField(null=True, verbose_name='Дата и время закрытия заявки')),
                ('employee_start', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_start', to='employeesapp.Employee', verbose_name='Отправитель')),
                ('mainproblem', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ticketsapp.MainProblem', verbose_name='Типовая проблема')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employeesapp.Employee', verbose_name='Исполнитель')),
                ('subproblem', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ticketsapp.SubProblem', verbose_name='Проблема')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-timestarted'],
                'permissions': (('can_view_allticketslist', 'Может просматривать все заявки'), ('can_view_myticketslist', 'Может просматривать свои заявки'), ('can_view_imperformer_ticketslist', 'Может просматривать назначенные заявки'), ('can_add_tickets', 'Может добавлять заявки'), ('can_edit_all_tickets', 'Может изменять все заявки'), ('can_edit_my_tickets', 'Может изменять свои заявки'), ('can_delete_my_tickets', 'Может удалять свои заявки')),
            },
        ),
    ]
