# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SubProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subproblemname', models.CharField(max_length=50, verbose_name='Подпроблема')),
            ],
        ),
        migrations.AddField(
            model_name='mainproblem',
            name='mainpoblemname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsapp.SubProblem'),
        ),
    ]
