# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainproblemname', models.CharField(max_length=30, null=True, verbose_name='Типовая проблема')),
            ],
        ),
        migrations.CreateModel(
            name='SubProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subproblemname', models.CharField(max_length=30, null=True, verbose_name='Проблема')),
                ('mainproblem', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ticketsapp.MainProblem', verbose_name='Типовая проблема')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Открыта'), ('INWORK', 'В работе'), ('CLOSED', 'Закрыта')], default='OPEN', max_length=50, verbose_name='Статус заявки')),
                ('priority', models.CharField(choices=[('LOW', 'Низкий'), ('NORMAL', 'Обычный'), ('HIGH', 'Высокий')], default='NORMAL', max_length=50, verbose_name='Приоритет')),
                ('description', models.CharField(max_length=300, verbose_name='Описание проблемы')),
                ('note', models.CharField(blank=True, default='-', max_length=300, null=True, verbose_name='Примечание')),
                ('timestarted', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время подачи заявки')),
                ('timeclosed', models.DateTimeField(null=True, verbose_name='Дата и время закрытия заявки')),
                ('employee_start', models.CharField(default='Иванов И.И.', max_length=30, verbose_name='Подал заявку')),
                ('performer', models.CharField(default=None, max_length=30, null=True, verbose_name='Исполнитель')),
                ('mainproblem', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ticketsapp.MainProblem', verbose_name='Типовая проблема')),
                ('subproblem', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ticketsapp.SubProblem', verbose_name='Проблема')),
            ],
        ),
    ]
