# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Открыта'), ('INWORK', 'В работе'), ('CLOSED', 'Закрыта')], max_length=50, verbose_name='Статус заявки')),
                ('priority', models.CharField(choices=[('LOW', 'Низкий'), ('NORMAL', 'Обычный'), ('HIGH', 'Высокий')], max_length=50, verbose_name='Приоритет')),
                ('description', models.CharField(max_length=300, verbose_name='Описание проблемы')),
                ('timestarted', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время подачи заявки')),
                ('timeclosed', models.DateTimeField(verbose_name='Дата и время закрытия заявки')),
            ],
        ),
        migrations.RemoveField(
            model_name='mainproblem',
            name='mainpoblemname',
        ),
        migrations.AddField(
            model_name='mainproblem',
            name='mainproblemname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='subproblem',
            name='mainproblem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ticketsapp.MainProblem'),
        ),
        migrations.AlterField(
            model_name='subproblem',
            name='subproblemname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='mainproblem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ticketsapp.MainProblem'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subproblem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ticketsapp.SubProblem'),
        ),
    ]
