# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-timestarted'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='mainproblem',
            name='mainproblemname',
            field=models.CharField(max_length=50, null=True, verbose_name='Типовая проблема'),
        ),
        migrations.AlterField(
            model_name='subproblem',
            name='subproblemname',
            field=models.CharField(max_length=50, null=True, verbose_name='Проблема'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Открыта'), ('INWORK', 'В работе'), ('CLOSED', 'Выполнено')], default='OPEN', max_length=50, verbose_name='Статус заявки'),
        ),
    ]
