# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsapp', '0002_auto_20181022_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='performer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employeesapp.Employee', verbose_name='Исполнитель'),
        ),
    ]
