# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsapp', '0002_auto_20181017_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Низкий'), ('NORMAL', 'Обычный'), ('HIGH', 'Высокий')], default='NORMAL', max_length=50, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='timeclosed',
            field=models.DateTimeField(null=True, verbose_name='Дата и время закрытия заявки'),
        ),
    ]
