# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsapp', '0003_auto_20181018_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproblem',
            name='mainproblemname',
            field=models.CharField(max_length=30, null=True, verbose_name='Типовая проблема'),
        ),
        migrations.AlterField(
            model_name='subproblem',
            name='mainproblem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ticketsapp.MainProblem', verbose_name='Типовая проблема'),
        ),
        migrations.AlterField(
            model_name='subproblem',
            name='subproblemname',
            field=models.CharField(max_length=30, null=True, verbose_name='Проблема'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='mainproblem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ticketsapp.MainProblem', verbose_name='Типовая проблема'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Открыта'), ('INWORK', 'В работе'), ('CLOSED', 'Закрыта')], default='OPEN', max_length=50, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subproblem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ticketsapp.SubProblem', verbose_name='Проблема'),
        ),
    ]
