# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsapp', '0004_auto_20181030_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='employee_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_start', to='employeesapp.Employee'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='performer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performer', to='employeesapp.Employee'),
        ),
    ]
