# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsapp', '0005_auto_20181030_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='employee_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_start', to='employeesapp.Employee', verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='performer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employeesapp.Employee', verbose_name='Исполнитель'),
        ),
    ]
