# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsapp', '0006_auto_20181101_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='employee_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_start', to='employeesapp.Employee', verbose_name='Отправитель'),
        ),
    ]
