# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsapp', '0008_auto_20181109_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='userhostname',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Имя компьютера'),
        ),
    ]
