# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsapp', '0008_auto_20181019_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[('LOW', 'Низкий'), ('NORMAL', 'Обычный'), ('HIGH', 'Высокий')], default='NORMAL', max_length=50, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[('OPEN', 'Открыта'), ('INWORK', 'В работе'), ('CLOSED', 'Закрыта')], default='OPEN', max_length=50, verbose_name='Статус заявки'),
        ),
    ]
