# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsapp', '0010_auto_20181203_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['-timestarted'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
