# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsapp', '0012_auto_20181203_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainproblem',
            options={'ordering': ['mainproblemname'], 'verbose_name': 'Типовая проблема', 'verbose_name_plural': 'Типовые проблемы'},
        ),
        migrations.AlterModelOptions(
            name='subproblem',
            options={'ordering': ['subproblemname'], 'verbose_name': 'Проблема', 'verbose_name_plural': 'Проблемы'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-timestarted'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
