# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsapp', '0013_auto_20181203_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainproblem',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['mainproblemname'], 'verbose_name': 'Типовая проблема', 'verbose_name_plural': 'Типовые проблемы'},
        ),
        migrations.AlterModelOptions(
            name='subproblem',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['subproblemname'], 'verbose_name': 'Проблема', 'verbose_name_plural': 'Проблемы'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['-timestarted'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
