# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=10000, verbose_name='Контент')),
                ('type', models.CharField(choices=[('Основные новости', 'MAIN'), ('Новости портала', 'PORTAL')], max_length=50, verbose_name='Тип новости')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['title'],
            },
        ),
    ]
